"""Add Inventory Model

Revision ID: 8523721fd2a6
Revises: ac286babe5ea
Create Date: 2023-03-28 14:57:16.607280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8523721fd2a6'
down_revision = 'ac286babe5ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('stores_id', sa.Integer(), nullable=True),
    sa.Column('owners_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stores_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['owners_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplies')
    # ### end Alembic commands ###
